[project]
name = "learning-litestar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "litestar[sqlalchemy,standard]>=2.15.2",
    "pwdlib[argon2]>=0.2.1",
]
